### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by marshall993** [jlengstorf/instagram-feed#1]
Came across your git and wanted to give this a try, loved the simplicity, unfortunately, this is not in working order. Have you accommodated Instagrams latest API changes?

**Comment by jlengstorf** [comment]
Hey, @marshall993 — this is still working. There were two issues:
1. jQuery was being loaded without HTTPS, which was causing an error.
2. The IG token in the demo was expired. I've updated it.

You can see it working here now: https://code.lengstorf.com/instagram-feed/

However, this is a janky way if you're planning to add this on a live website. The token doesn't live long, so it'll break at random. For a more robust solution, you'd need to add a server-side auth flow to update that token regularly.
